# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CW1_CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CW1_CocoaPods
  pod 'Alamofire', '~> 5.4'
end
